# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Cesar Ramirez
tagline:          'Tagline goes here!'
description:      ''
url:              http://cesarandres.com

author:
  name:           'Cesar Ramirez'
  url:            https://plus.google.com/+CesarRamirezSanchez

paginate:         5

github:
  repo:           https://github.com/cesarramirez/
