# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cesar Ramirez
url:              https://cramsan.com

author:
  name:           'Cesar Ramirez'
  url:            https://cramsan.com

paginate:         5
gems:             [jekyll-paginate]
