---
title: Cramsan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
url: https://cramsan.com
author:
  name: Cesar Ramirez
  url: https://cramsan.com/
  email: contact@cramsan.com
paginate: 15
plugins:
- jekyll-paginate
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- scripts
- no_index
- _wiki
