---
title: "Cramsan"
timezone: UTC
collections:
  resources:
    output: true
permalink: pretty
url: https://cramsan.com
author:
  name: Cesar Ramirez
  url: https://cramsan.com/
  email: contact@cramsan.com
paginate: 15
gems:
- jekyll-paginate
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- scripts
- no_index
- _wiki
