# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cesar Ramirez
url:              http://cesarandres.com

author:
  name:           'Cesar Ramirez'
  url:            https://plus.google.com/+CesarRamirezSanchez

paginate:         5
gems:             [jekyll-paginate,jekyll-sitemap]