---
title: "Cesar Ramirez"
timezone: UTC
collections:
  resources:
    output: true
highlighter: pygments
permalink: pretty
url: https://cramsan.com
author:
  name: Cesar Ramirez
  url: https://cramsan.com/
  email: contact@cramsan.com
paginate: 15
plugins:
- jekyll-paginate
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- scripts
