site_name: Wiki
site_dir: '../wiki'
nav:
    - Home: index.md
    - Gaming: gaming.md
    - Utilities: utilities.md
    - About: about.md
theme: 
    repo_name: 'CRamsan/cramsan.github.io'
    repo_url: 'https://github.com/CRamsan/cramsan.github.io'
    favicon: 'assets/images/favicon.ico'
    name: material
    icon:
        logo: 'material/home'
    palette:
        primary: 'teal'
        accent: 'teal'
    language: 'en'
    extra:
        search:
            language: 'en'
        social:
            - type: 'github'
              link: 'https://github.com/CRamsan'
            - type: 'twitter'
              link: 'https://twitter.com/cramsan_dev'
extra_css:
    - css/cramsan_wiki.css
google_analytics:
    - 'UA-93675007-1'
    - 'auto'
 